### ISSUE TITLE
ERROR: UndefVarError: SliceUnivariate not defined

### ISSUE THREAD

**Issue by michaellindon** [brian-j-smith/Mamba.jl#103]
Seems I'm falling at the first hurdle with this...

```
julia> theta1 = SliceUnivariate([0.0, 0.0, 0.0], width, logf)
ERROR: UndefVarError: SliceUnivariate not defined
```

I'm using Julia Version 0.4.6. Am I missing something?

**Comment by bdeonovic** [comment]
did you do ``using Mamba``?

**Comment by michaellindon** [comment]
I did

**Comment by michaellindon** [comment]
![screenshot from 2016-08-30 10-11-27](https://cloud.githubusercontent.com/assets/4892846/18092427/43c0741e-6e9a-11e6-9ec8-14dacc1d4d82.png)

**Comment by brian-j-smith** [comment]
Interesting. That exact code works for me.  It comes from the package tests, which are passing on travis and PackageEvaluator.jl  Could you do a ``Pkg.status()`` to check and post which version of Mamba you have installed?  Mamba 0.9.2 is the latest version for julia 0.4.  ``Pkg.update()`` should update you to the latest version if not there already.

**Comment by michaellindon** [comment]
Ah indeed I was using an old version
 - Mamba                         0.7.3

ill be more careful to update first to see if it resolves issues in future

**Comment by brian-j-smith** [comment]
Great.  Glad to hear that was it.
