### ISSUE TITLE
Support do-block syntax

### ISSUE THREAD

**Issue by rofinn** [brian-j-smith/Mamba.jl#121]
If the node constructors took a `Function` as the first argument then nodes could be written like:

```julia
theta = Stochastic(1, true) do alpha, beta
    Gamma(alpha, 1 / beta)
end
```

**Comment by brian-j-smith** [comment]
Done.  Changes to accept functions as the first arguments of the Logical and Stochastic constructors are now in the master branch and will be in the next package release.

**Comment by rofinn** [comment]
Great, thank you!
