### ISSUE TITLE
The choice of Automatic Differentiation in Mamba

### ISSUE THREAD

**Issue by boathit** [brian-j-smith/Mamba.jl#137]
I noticed that the [AD](https://github.com/brian-j-smith/Mamba.jl/blob/master/src/model/simulation.jl#L50) adopted in `Mamba.jl` is still based on the finite difference method from `Calculus.jl`, is there any reason that does not use the more efficient implementation in `ForwardDiff.jl`?

**Comment by bdeonovic** [comment]
When I have some free time I plan on implementing ForwardDiff for autodiff in Mamba.

**Comment by boathit** [comment]
Great.
