### ISSUE TITLE
Method definition conflict between Mamba.jl and Distributions.jl

### ISSUE THREAD

**Issue by jojal5** [brian-j-smith/Mamba.jl#170]
I'm using Mamba in Extremes.jl for performing Bayesian extreme value analysis in Julia (v1.4-v1.5). Both Mamba.jl (v0.12) and Distribution.jl (v0.23) are required in Extremes.jl. When compiling Extremes.jl with the command `using Extremes`, the following message is prompted:

WARNING: Method definition (::Type{Distributions.MvNormal{T, Cov, Mean} where Mean<:(AbstractArray{T, 1} where T) where Cov<:(PDMats.AbstractPDMat{T} where T<:Real) where T<:Real})(AbstractArray{T<:Real, 1}, AbstractArray{U<:Real, 2}) where {T<:Real, U<:Real} in module Distributions at /Users/jalbert/.julia/packages/Distributions/jFoHB/src/multivariate/mvnormal.jl:211 overwritten in module Mamba at /Users/jalbert/.julia/packages/Mamba/Jotzr/src/distributions/constructors.jl:19.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition (::Type{Distributions.MvNormal{T, Cov, Mean} where Mean<:(AbstractArray{T, 1} where T) where Cov<:(PDMats.AbstractPDMat{T} where T<:Real) where T<:Real})(AbstractArray{T<:Real, 1}, AbstractArray{U<:Real, 1}) where {T<:Real, U<:Real} in module Distributions at /Users/jalbert/.julia/packages/Distributions/jFoHB/src/multivariate/mvnormal.jl:217 overwritten in module Mamba at /Users/jalbert/.julia/packages/Mamba/Jotzr/src/distributions/constructors.jl:22.
  ** incremental compilation may be fatally broken for this module **

It does not affect the functionalities of Extremes.jl, but it is a bit annoying. Is there a workaround for this issue?

Again, thanks for the excellant Mamba package.

**Comment by brian-j-smith** [comment]
Hi @jojal5.  I don't like warnings either.  Do they go away if you check out the latest commits in the master branch via ``develop Mamba`` at the Pkg command prompt?  If so, I'll plan to push those out in a new release of the package.

**Comment by jojal5** [comment]
Hi @brian-j-smith, thank you for the quick reply. Using the version of Mamba on the master branch (v0.12.4), the warnings vanish when compiling Extremes. I'll look forward to the next release of Mamba!
