### ISSUE TITLE
API to handle nested dimensional stochastic arguments

### ISSUE THREAD

**Issue by binarybana** [brian-j-smith/Mamba.jl#2]
I'm trying to implement a model [(all code and errors here)](https://gist.github.com/binarybana/4fbb4e6dfc5d30da234e) where each lambda is two dimensional (across i and j), and is distributed according to a multivariate normal. (see \lambda in plate model below but ignore the y variable).

![plate_model](https://cloud.githubusercontent.com/assets/392846/3577424/9069b716-0b9c-11e4-9075-472bc58b38fa.png)

When defining the stochastic variable lambda in the model section, I don't see how to do this other than as a one dimensional array of Multivariate Normal distributions (as seen on line 32), but then when I try to initialize the chain, it gives me the error:

``` julia
julia> include("mpm.jl")
MCMC Simulation of 10000 Iterations x 4 Chains...

exception on 1: ERROR: `convert` has no method matching convert(::Type{Float64}, ::Array{Float64,1})
 in copy! at abstractarray.jl:149
 in setinits! at /home/jason/.julia/Mamba/src/model/dependent.jl:120
 in setinits! at /home/jason/.julia/Mamba/src/model/initialization.jl:26
 in mcmc_sub! at /home/jason/.julia/Mamba/src/model/mcmc.jl:28
 in anonymous at multi.jl:652
 in run_work_thunk at multi.jl:613
 in remotecall_fetch at multi.jl:686
 in remotecall_fetch at multi.jl:701
 in anonymous at task.jl:1348
ERROR: `convert` has no method matching convert(::Type{Chains}, ::MethodError)
 in getindex at array.jl:121
 in mcmc at /home/jason/.julia/Mamba/src/model/mcmc.jl:20
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
while loading /home/jason/GSP/research/samc/mamba/mpm.jl, in expression starting on line 47
```

So it looks like it is trying to convert the array of arrays into an array of floats. I've also tried considering it as a two dimensional stochastic variable (with matrix initialization), but then I don't see how to represent the stochastic variable (you can see the error message at the gist above).

Hopefully that wasn't completely unintelligible. Thanks!

**Comment by binarybana** [comment]
@brian-j-smith, close! I'm *about* to graduate, have a third kid on the way, and am still in the job application process. :)

Thanks for the detailed writeup and feature adds in Mamba.jl, it's exciting seeing this package grow so quickly.

**Comment by brian-j-smith** [comment]
Haha.  Congratulations on all the excitement going on in your life.  That’s great!  Best of luck in the job search.
