### ISSUE TITLE
Triangular not defined on Julia 0.4-pre

### ISSUE THREAD

**Issue by goedman** [brian-j-smith/Mamba.jl#23]
Hi Brian,

I've been trying to figure out where Triangular is defined. I see it is being used in MixedModels, but not in PDMats.

Is this just one of those things that will be fixed in due course, when v0.4+packages matures?

Regards,
Rob

ERROR: LoadError: LoadError: UndefVarError: Triangular not defined
 in include at ./boot.jl:249
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:249
 in include_from_node1 at ./loading.jl:128
 in reload_path at ./loading.jl:152
 in _require at ./loading.jl:67
 in require at ./loading.jl:52
while loading /Users/rob/.julia/v0.4/Mamba/src/distributions/pdmats2.jl, in expression starting on line 109
while loading /Users/rob/.julia/v0.4/Mamba/src/Mamba.jl, in expression starting on line 32

**Comment by brian-j-smith** [comment]
Hi Rob,

I noticed the Triangular error with recent 0.4 nightlies as well.  Triangular is one of the matrix types in the julia 0.3 core.  In looking at the recent documentation at http://docs.julialang.org/en/latest/manual/linear-algebra/, it appears the 0.3 type is going to be replaced in 0.4 with UpperTriangular and LowerTriangular.

BTW, you might have noticed that I started a new julia-0.4 branch and have made some compatibility changes there.  However, I will probably wait until the 0.4 feature set has stabilized a bit more before devoting a lot of time to that branch.  Of course, anyone else is welcome to work on it in the meantime.

Thanks,
Brian

**Comment by brian-j-smith** [comment]
This issue appears to be the same as the one raised in https://github.com/brian-j-smith/Mamba.jl/issues/22.  To avoid a redundancy and to help me keep track of unique issues, I'm going to close this one and leave the other open.

**Comment by goedman** [comment]
HI Brian,

Thanks for the update.

I agree, it is a delicate decision when to put in the effort to make packages run on 0.4. The majority of warnings are from packages Mamba imports anyway.

Hadn’t noticed the 0.4 branch yet, pretty busy with some other stuff (aren’t we all?). Will have a look at the 0.4 branch and the Upper/LowerTriangular stuff. 

Regards,
Rob J. Goedman
goedman@mac.com
