### ISSUE TITLE
Warning: discrete_color is now called color_discrete on Julia 0.3.5

### ISSUE THREAD

**Issue by goedman** [brian-j-smith/Mamba.jl#24]
Hi Brian,

Testing Stan-2.6.0 this evening I noticed below warning. I think this started after upgrading to Gadfly 0.3.11.

WARNING: discrete_color(; levels=nothing,order=nothing,preserve_order=true) is deprecated, use color_discrete(; levels=levels,order=order,preserve_order=preserve_order) instead.

It applies to plot.jl and a quick test after find-and-replace (4 occurrences) fixed the problem.

Regards,
Rob

**Comment by brian-j-smith** [comment]
Got it.  The fix is in the master branch now and will be in the next release.

**Comment by goedman** [comment]
Thanks Brian!

**Comment by brian-j-smith** [comment]
Mamba 0.4.5 was just released with a fix for the Gadfly function renaming of `discrete_color` to `color_discrete`.
