### ISSUE TITLE
Feature Request: API to handle Arrays of Multivariate Distributions

### ISSUE THREAD

**Issue by bdeonovic** [brian-j-smith/Mamba.jl#27]
Right now, the package only supports return types that are either a single univariate/multivariate/matrix distribution or an array of univariate distributions. 

For some problems this can be remedied if the array of multivariate distributions can be expressed as a single multivariate distribution (see issue https://github.com/brian-j-smith/Mamba.jl/issues/2 for an example). 

However, a more general solution should be made available.

**Comment by brian-j-smith** [comment]
Support for arrays of multivariate distributions will be in *Mamba 0.6*.  The support is described in and can be further discussed in #44.
