### ISSUE TITLE
Use file.exists to check for addons.jl before trying to open it

### ISSUE THREAD

**Issue by dmbates** [brian-j-smith/Mamba.jl#28]
I will prepare a pull request with a fix for this issue.  Presently `Mamba/src/Mamba.jl` uses a try/catch block to optionally load the file `Mamba/usr/addons.jl`, producing error reports if the file does not exist.  The errors are caught but it would be cleaner to check that it exists before trying to source the file.

**Comment by brian-j-smith** [comment]
Agreed.  Getting rid of the error reports by using file.exists would be cleaner.  If you submit the pull request, I’ll merge it in.  Thanks.

**Comment by brian-j-smith** [comment]
Thanks for the pull.  It's merged in and on deck for the next release.
