### ISSUE TITLE
Is there a way to turn off the progress statements in a call to mcmc?

### ISSUE THREAD

**Issue by dmbates** [brian-j-smith/Mamba.jl#29]
Particularly when sampling multiple chains in different processes (which is a great capability, by the way) the progress messages are interleaved and not of much value.  I would like to suppress them.

**Comment by brian-j-smith** [comment]
@dmbates - We'll plan to include an option to suppress the progress messages in the next release.  It's a feature we had implemented internally a while back while experimenting with different ways of showing progress.

**Comment by brian-j-smith** [comment]
In just-released *Mamba 0.4.6*, there is a `verbose` Boolean argument added to the `mcmc` methods to suppress the progress messages.  Documentation is [here](http://mambajl.readthedocs.org/en/latest/mcmc/model.html#mcmc).  In short, set `verbose=false` to suppress.

The current implementation suppresses all messages.  I'll leave this issue open for a while in case there is interest in having some minimal sort of feedback provided on the progress or, say, the expected runtime.

**Comment by dmbates** [comment]
Thanks.
