### ISSUE TITLE
Incorporating inputs that are neither sources nor targets

### ISSUE THREAD

**Issue by dmbates** [brian-j-smith/Mamba.jl#31]
This is a question rather than an issue, per se.  @brian-j-smith, if you would prefer that I correspond directly with you instead of filing an issue please tell me.

I have been looking at the simple `line` example and using that to refresh my memory on canonical parameters, etc.  In the `Gibbs_beta` sampler in that example, the products `xmat' * xmat` and `xmat' * y` are computed for every sample.  Also a couple of matrix inverses are evaluated, probably without taking advantage of the Cholesky factorization that is already available.  Using `PDMat` types and the `MvNormalCanon` distribution helps eliminate some of the inverses but I still wonder about computing the products for every sample.

I tried to specify `XtX` and `Xty` in the data (the `line` Dict) but, as they are neither sources nor targets for the Stochastic or Logical nodes in the model, they don't get incorporated in `model.nodes`.  They are only used in the Sampler for `beta`.  Is there a way of forcing these data values into the nodes of the model?

**Comment by dmbates** [comment]
I did find that I could incorporate these constants by setting the key/value pairs in `model.nodes` but I doubt that is the recommended approach.

**Comment by brian-j-smith** [comment]
Another way would be to reference those `line` Dict elements in one of the logical or stochastic nodes, e.g.

```julia
model = Model(

  y = Stochastic(1,
    @modelexpr(mu, s2,
      MvNormal(mu, sqrt(s2))
    ),
    false
  ),

  mu = Logical(1,
    @modelexpr(xmat, beta, XtX, Xty,
      xmat * beta
    ),
    false
  ),

  beta = Stochastic(1,
    :(MvNormal(2, sqrt(1000)))
  ),

  s2 = Stochastic(
    :(InverseGamma(0.001, 0.001))
  )

)
```

Even though `XtX` and `Xty` are not used in the logical node above, the references will cause them to be loaded into the model and be available to samplers.  Probably need to come up with something more intuitive for this situation.

P.S. Questions here are fine.  You're also welcome to email me at my uiowa account if you like.

**Comment by brian-j-smith** [comment]
Or, it should work to create them as logical nodes as shown below.  Since those nodes do not depend on any others that get updated, they would only be calculated once in mcmc runs.

```julia
model = Model(

  y = Stochastic(1,
    @modelexpr(mu, s2,
      MvNormal(mu, sqrt(s2))
    ),
    false
  ),

  mu = Logical(1,
    @modelexpr(xmat, beta,
      xmat * beta
    ),
    false
  ),
  
  XtX = Logical(2,
    @modelexpr(xmat,
      xmat' * xmat
    ),
    false
  ),

  Xty = Logical(1,
    @modelexpr(xmat, y,
      xmat' * y
    ),
    false
  ),

  beta = Stochastic(1,
    :(MvNormal(2, sqrt(1000)))
  ),

  s2 = Stochastic(
    :(InverseGamma(0.001, 0.001))
  )

)
```

**Comment by goedman** [comment]
Brian, that dependency you derive from the DAG graph?

This thread has certainly helped me to get a better understanding of predict() to get prior predictive distribution samples as well.

**Comment by dmbates** [comment]
@brian-j-smith Would the second approach end up recalculating `XtX` and `Xty` at every iteration? Other logical nodes like `mu` do need to be reevaluated at each iteration?  Does using the DAG detect that `mu` depends on `beta` but `XtX` depends only on `xmat` and therefore does not need updating?

**Comment by brian-j-smith** [comment]
Big picture view...  The DAG is constructed from dependencies in the model specification.  The DAG is then used in conjunction with the node types and sampler specifications to determine which nodes need to be updated when at each iteration.

Consequently, in the second approach, the program will recognize that logical nodes `XtX` and `Xty` only need to be initialized once and not recalculated at every iteration.  Nodes like `mu` that do depend on things that change (`beta`) will be recalculated.  So, answers to @dmbates are "no", "yes", and "yes".

I like the second approach because it produces a DAG that more accurately reflects dependencies than the first approach.  Although, both approaches should work here.
