### ISSUE TITLE
mu is being calculated twice in the line example

### ISSUE THREAD

**Issue by dmbates** [brian-j-smith/Mamba.jl#32]
In the `line` example `mu` is a Logical node evaluated as `xmat * beta` in the model specification.  In the `Gibbs_s2` sampler, the residual sum of squares is evaluated as `sum((y - xmat*beta).^2)` which could be written `sum((y - mu).^2)` or, even better, `sumabs2(y - mu)`.

**Comment by brian-j-smith** [comment]
Nice suggestions.  The last one is in the master branch now.
