### ISSUE TITLE
Use Showoff package for printing tables

### ISSUE THREAD

**Issue by dmbates** [brian-j-smith/Mamba.jl#34]
@dcjones has written the `Showoff` package that makes it easy to align numeric values in a column.  I think that a combination of Showoff and using `show(io,...)` or `print(io,...)` calls in the show methods can make the output of `describe` and `hpd` easier to read.  It should also be possible to use mime types to create tables that show up as such in IJulia notebooks.

I would be willing to take a first cut at this.  Should I create a new branch from the master branch or from the develop branch?

**Comment by brian-j-smith** [comment]
Better formatting of posterior summary statistics would be great.  The current approach is pretty basic.  I would be happy to merge in any improvements on that.  I'm not familiar with @dcjones *Showoff* package, but have been impressed with his *Gadfly* one.  His packages seem well-written and maintained.

BTW, early on, I was looking at the `CoefTable` type in the *StatsBase* package and how it is displayed.  That might be worthwhile considering, but feel free to use whatever approach you like.

Do go ahead and branch off of the develop branch.

**Comment by dmbates** [comment]
If someone (like me) gets really ambitious it would be good to have methods for `Base.writemime` so that HTML or CSV or TSV tables could be produced.  I am also toying with the idea of using Unicode subscript characters instead of the `[1]` notation for vector indices in the colnames.

**Comment by dmbates** [comment]
An example using this output is the MvGaussian notebook which can be viewed at

http://nbviewer.ipython.org/github/dmbates/juliaboxnotebooks/

**Comment by brian-j-smith** [comment]
Those notebooks are nice.  Makes me think it's time for me to learn how to use IJulia.

Mime type methods would be good to have.  A latex one too might get a fair amount of use.  Subscripted indices would be cool.

**Comment by goedman** [comment]
Yes, I'd been pretty convinced by several of Steven Johnson's Notebooks and JuliaBox stuff, but these examples are equally impressive and convincing!

**Comment by dmbates** [comment]
Closed by #35
