### ISSUE TITLE
graph2dot should use an IObuffer

### ISSUE THREAD

**Issue by dmbates** [brian-j-smith/Mamba.jl#36]
Instead of concatenating strings in the `graph2dot` function it would be better to write to an `IOBuffer` and apply `bytestring` to get a string representation.  It would be handy if the string itself could be returned so that GraphViz.Graph could be applied to it in environments like `IJulia` that can draw graphs directly.

**Comment by dmbates** [comment]
@brian-j-smith  I would be happy to create a pull request with this change if you thought it worthwhile.

**Comment by brian-j-smith** [comment]
Have at it.

**Comment by dmbates** [comment]
Closed by #37
