### ISSUE TITLE
Column headers on hpd table are incorrect

### ISSUE THREAD

**Issue by dmbates** [brian-j-smith/Mamba.jl#38]
It's a minor point but the columns for, say, a set of 95% HPD intervals, are labelled 2.5% and 97.5% and that is not accurate because these aren't quantiles.  However, I am not sure what they should be called.  They are the lower and upper endpoints of the 95% HPD interval and I can't think of a way of communicating both the lower and upper and the probability content in concise column headers.

**Comment by brian-j-smith** [comment]
That is a good point.  HPD intervals do not necessarily put equal probabilities in the tails.  Perhaps label these 95% Lower Bound and 95% Upper Bound?

**Comment by dmbates** [comment]
Generally I prefer to avoid abbreviations but I think I would be inclined to use "95% Lower Bd" and "95% Upper Bd" so that the column headers did not end up being considerably wider than the contents.  It may not be worthwhile saving 3 characters, though.

**Comment by brian-j-smith** [comment]
If no objections, I'll plan on using "95% Lower" and "95% Upper", and even use the showoff function to make the number (95) in the label look nice.

The goal is to release the next version tonight.  So, if you have any last minute changes to include or showstoppers, let me know.

**Comment by dmbates** [comment]
Sounds good.  I'm looking forward to the new release.
