### ISSUE TITLE
Type error on load

### ISSUE THREAD

**Issue by fonnesbeck** [brian-j-smith/Mamba.jl#39]
Following a clean install on Julia 0.3.6, loading Mamba results in an error from `instantiate_type`.

![image](https://cloud.githubusercontent.com/assets/81476/7515931/f9ab5044-f490-11e4-9bbb-4dd65b8f1cc6.jpg)

**Comment by brian-j-smith** [comment]
Hi,

I don't seem to be getting this error.  Could you try posting your results from `Pkg.status()`?  Thanks.

**Comment by fonnesbeck** [comment]
I get the following:

    Pkg.status()
    1 required packages:
     - Mamba                         0.4.7
    39 additional packages:
     - ArrayViews                    0.6.2
     - BinDeps                       0.3.11
     - Cairo                         0.2.26
     - Calculus                      0.1.6
     - Codecs                        0.1.4
     - Color                         0.4.4
     - Compat                        0.4.3
     - Compose                       0.3.11
     - Contour                       0.0.6
     - DataArrays                    0.2.14
     - DataFrames                    0.6.5
     - DataStructures                0.3.8
     - Dates                         0.3.2
     - Distances                     0.2.0
     - Distributions                 0.7.3
     - Docile                        0.4.11
     - DualNumbers                   0.1.3
     - FixedPointNumbers             0.0.7
     - GZip                          0.2.15
     - Gadfly                        0.3.11
     - Graphics                      0.1.0
     - Graphs                        0.5.4
     - Grid                          0.3.8
     - Hexagons                      0.0.3
     - ImmutableArrays               0.0.7
     - Iterators                     0.1.7
     - JSON                          0.4.3
     - KernelDensity                 0.1.0
     - Loess                         0.0.3
     - NaNMath                       0.0.2
     - Optim                         0.4.1
     - PDMats                        0.3.3
     - Reexport                      0.0.2
     - SHA                           0.0.4
     - Showoff                       0.0.4
     - SortingAlgorithms             0.0.5
     - StatsBase                     0.6.15
     - URIParser                     0.0.5
     - WoodburyMatrices              0.0.1

**Comment by brian-j-smith** [comment]
The package versions look ok.  Unfortunately, I'm still not having any luck reproducing the error.  So far, I've successfully tested Mamba on the following:

* Personal computer (julia 0.3.6, windows, fresh install)
* 2 separate personal computers (julia 0.3.8, windows)
* Travis-ci.org (julia 0.3.8, linux, fresh install)
* Juliabox.org (julia 0.3.6)

I'm not sure what's going on.  Maybe try deleting (or temporarily moving) your `/home/sense/.julia/v0.3` directory and reinstalling (`Pkg.add`) the julia packages, and/or upgrading to julia 0.3.8?

**Comment by fonnesbeck** [comment]
This seems to have disappeared on creating a new instance of my VPS. Sorry for the trouble.

**Comment by brian-j-smith** [comment]
No worries.  Glad to hear it's working for you now.
