### ISSUE TITLE
Mamba 0.6 release notes and changes

### ISSUE THREAD

**Issue by brian-j-smith** [brian-j-smith/Mamba.jl#44]
This is an informational post to announce a user interface change coming in the next version of *Mamba* (0.6).  Barring any showstoppers, 0.6 will be released this weekend (8/1-8/2) and require **julia 0.4** for installation.  *Mamba 0.4* will continue to run on **julia 0.3**.

Several internal changes have been made, most of which should be transparent to users.  They are summarized in the [NEWS.md](https://github.com/brian-j-smith/Mamba.jl/blob/release-0.6/NEWS.md) file and reflected in the package [documentation](http://mambajl.readthedocs.org/en/release-0.6/). One change that will affect the user interface for model specification is added support for `MultivariateDistribution` arrays in stochastic nodes (Issues #2 and #27).  In particular, arrays in stochastic nodes must now be declared as a `UnivariateDistribution[]` or as a `MultivariateDistribution[]`. In previous package versions, arrays could be declared as a generic `Distribution[]` array.  The generic approach will not be allowable due to the need to distinguish between arrays of univariate and multivariate distributions.

The documentation for [stochastic nodes](http://mambajl.readthedocs.org/en/release-0.6/mcmc/dependent.html#stochastic) describes the types of supported distribution structures, including arrays.  Syntax for univariate and multivariate arrays is illustrated in the [Birats example](http://mambajl.readthedocs.org/en/release-0.6/examples/birats.html#example-birats) given below.

```julia
using Mamba

## Data
birats = Dict{Symbol,Any}(
  :N => 30, :T => 5,
  :x => [8.0, 15.0, 22.0, 29.0, 36.0],
  :Y => [151 199 246 283 320
         145 199 249 293 354
         147 214 263 312 328
         155 200 237 272 297
         135 188 230 280 323
         159 210 252 298 331
         141 189 231 275 305
         159 201 248 297 338
         177 236 285 350 376
         134 182 220 260 296
         160 208 261 313 352
         143 188 220 273 314
         154 200 244 289 325
         171 221 270 326 358
         163 216 242 281 312
         160 207 248 288 324
         142 187 234 280 316
         156 203 243 283 317
         157 212 259 307 336
         152 203 246 286 321
         154 205 253 298 334
         139 190 225 267 302
         146 191 229 272 302
         157 211 250 285 323
         132 185 237 286 331
         160 207 257 303 345
         169 216 261 295 333
         157 205 248 289 316
         137 180 219 258 291
         153 200 244 286 324],
  :mean => [0.0, 0.0],
  :var => [1.0e6 0.0
           0.0   1.0e6],
  :Omega => [200.0 0.0
               0.0 0.2]
)


## Model Specification
model = Model(

  Y = Stochastic(2,
    @modelexpr(beta, x, sigmaC, N, T,
      UnivariateDistribution[
        Normal(beta[i,1] + beta[i,2] * x[j], sigmaC)
        for i in 1:N, j in 1:T
      ]
    ),
    false
  ),

  beta = Stochastic(2,
    @modelexpr(mu_beta, Sigma, N,
      MultivariateDistribution[
        MvNormal(mu_beta, Sigma)
        for i in 1:N
      ]
    ),
    false
  ),

  mu_beta = Stochastic(1,
    @modelexpr(mean, var,
      MvNormal(mean, var)
    )
  ),

  Sigma = Stochastic(2,
    @modelexpr(Omega,
      InverseWishart(2, Omega)
    ),
    false
  ),

  sigma2C = Stochastic(
    :(InverseGamma(0.001, 0.001)),
    false
  ),

  sigmaC = Logical(
    @modelexpr(sigma2C,
      sqrt(sigma2C)
    )
  )

)


## Initial Values
inits = [
  Dict(:Y => birats[:Y], :beta => repmat([100 6], birats[:N], 1),
       :mu_beta => [0, 0], :Sigma => eye(2), :sigma2C => 1.0),
  Dict(:Y => birats[:Y], :beta => repmat([50 3], birats[:N], 1),
       :mu_beta => [10, 10], :Sigma => 0.3 * eye(2), :sigma2C => 10.0)
]


## Sampling Scheme
scheme = [AMWG([:beta, :mu_beta], repeat([10.0, 1.0], outer=[birats[:N] + 1])),
          AMWG([:Sigma], fill(1.0, 3)),
          Slice([:sigma2C], [10.0])]
setsamplers!(model, scheme)


## MCMC Simulations
sim = mcmc(model, birats, inits, 10000, burnin=2500, thin=2, chains=2)
describe(sim)
```

**Comment by gragusa** [comment]
@brian-j-smith The documentation link is missing from README.md.

**Comment by brian-j-smith** [comment]
Hi @gragusa - I'll add the documentation link back in with my next batch of changes (in a day or two).  In the meantime, you can click on the [![Docs](https://readthedocs.org/projects/mambajl/badge/?version=release-0.6)](http://mambajl.readthedocs.org/en/release-0.6/) or [![Docs](https://readthedocs.org/projects/mambajl/badge/?version=release-0.4)](http://mambajl.readthedocs.org/en/release-0.4/) badges at the top of the readme page.

**Comment by gragusa** [comment]
Thanks. I thought it was left out by mistake.
