### ISSUE TITLE
bug in mcmc(::ModelChains,...)

### ISSUE THREAD

**Issue by axsk** [brian-j-smith/Mamba.jl#65]
I think there is something wrong with the counter of iterations in mcmc(::ModelChains, ...).

``` julia
mc1 = mcmc(model, [...])
mc2 = mcmc(mc1, 100)
mc3 = mcmc(mc2, 100)
```
results in `ArgumentError: chain is missing its last iteration`.
Specifically mc2.model.iter is 300 whilst it should be 200.

**Comment by axsk** [comment]
Removing `mc2.model.iter += mc.model.iter` helped.
I think the increase of the iter counter is already done in the simulate! step.

**Comment by brian-j-smith** [comment]
Yes, you're right.  The increase is not needed and should be removed.  If you would like to create a pull request with the fix, feel free; otherwise, I'll do it and make a new release tomorrow.  Thanks.

**Comment by axsk** [comment]
Guess that one line is not worth the effort, I'll let you do the edit :)

OT: (Did not know where else to ask this nor did I want to open an Issue for what might not be one)
Reviewing the amm.jl code I wondered about [line 90](https://github.com/brian-j-smith/Mamba.jl/blob/master/src/samplers/amm.jl#L90):
`Sigma = (sd / p) * (tune.Mvv - tune.Mv * tune.Mv')`
Why does p appear in there?

**Comment by axsk** [comment]
And even stranger:
``` julia
  SigmaLm: Array(Float64,(13,13)) 13x13 Array{Float64,2}:
   431.539        417.138          0.0         …   0.0         0.0       
 -1094.87          84.6307       263.243           0.0         0.0       
    -8.24719       -6.32561       -1.54006         0.0         0.0       
    -0.0603697     -0.089554      -0.0170486       0.0         0.0       
    -0.000294187    0.000110255    7.07231e-5     -7.8939e-6   8.36366e-5
    -0.0109781     -0.0125368     -0.00273581  …   0.00191646  0.0       
    -0.00697352    -0.132813      -0.0151132       0.0         0.0       
     0.0896746      0.089695       0.0487108       0.0         0.0       
    -3.92582        0.038372       0.730782        0.0         0.0       
    -4.67156       -0.0903987      0.161233        0.0         0.0       
    -9.46621        1.67978        1.58091     …   0.0         0.0       
  3447.99           0.0            0.0             0.0         0.0       
     1.09696       -3.33728       -1.65789         0.0         0.0       
```
This is the adapted Covariance Matrix set by amm!. Shouldn't all the diagonal elements be positive?

**Comment by brian-j-smith** [comment]
I think it is correct, but welcome another set of eyes on this sampler.  So, let's see.

``p = m / (m + 1)`` where ``m = 0, 1, 2, ...`` is the iteration number.

At that line, ``Mvv = 1 / (m + 1) * \sum_{i=0}^m v_i v_i^\top`` and ``Mv = 1 / (m + 1) * \sum_{i=0}^m v_i = \bar{v}``.

Thus, ``1 / p * (Mvv - Mv * Mv') = 1 / m * (sum_{i=0}^m v_i v_i^\top - (m + 1) \bar{v} * \bar{v}^\top)`` should be the sample covariance matrix.

With respect to ``SigmaLm``, if ``F = cholfact(Sigma, :U, Val{true})`` is full-rank, then ``Sigma = SigmaLm * SigmaLm'`` will be positive definite.  The pivoted factorization ``SigmaLm = F[:P] * F[:L]`` need not be triangular or have positive diagonal elements.

**Comment by axsk** [comment]
Thanks for the explanation and the fix.
