### ISSUE TITLE
Avoid double evaluation of logpdf

### ISSUE THREAD

**Issue by axsk** [brian-j-smith/Mamba.jl#68]
Looking at the sampler codes I realized that each iteration of the sampler calls the logpdf twice, once for the current value and once for the proposal, e.g. in amm.jl:
``` julia
if rand() < exp(logf(x) - logf(v.value))
```
This results in (at least) double evaluation of the same x value, which could be avoided by storing that result.

To make it available to the specific sampling function (amm!) it would need to be stored in the corresponding Variate, and to allow constructing that value via the corresponding Sampler constructor (AMM) it would also need to be stored somewhere in the model (block-specific?).

As a side effect one could easily add the feature monitor the logpdf value of each iteration, which I would like to have for visualization / convergence analysis.

Edit: Maybe monitoring the logpdf is not that straightforward, as the logpdf! value for transformed variables also contains the adjustment summand accounting for the resulting non-symmetric transition kernels, thus not really holding the probabilities logpdf value :(
The only solution I can think of is handling that summand/factor seperately.

**Comment by brian-j-smith** [comment]
The reason for the two logpdf evaluations is that the function may depend on model parameters that are updated by other samplers, between calls to amm.  Thus, it cannot generally be assumed that a logpdf value computed in one call of amm is applicable to the next call.

For monitoring, there is a logpdf method described [here](http://mambajl.readthedocs.org/en/latest/mcmc/chains.html#model-based-inference) to get the values from a ``ModelChains`` object.  It's a post-processing generalization of what you may be looking for.

**Comment by axsk** [comment]
I now see why this is a problem, seems we're running into the hard world of cache invalidation here.
In my specific setting evaluation of the logpdf function actually involves integrating a differential equation, and thus consumes about 99% of the time. Using caching thus results halving the computational time of the markov chain.

If more users have slow logpdf's we might start thinking about the caching again.

For now I will implement the caching in my logpdf function. For storing the logpdf value I will probably use an extra stochastic node with a custom noop-sampler storing the cached logpdf.

**Comment by axsk** [comment]
Caching got more difficult then I thought.
the unlist, list part actually transforms the values everytime, resulting in different arguments to the logpdf function even on rejections :(
