### ISSUE TITLE
Noticed below error on Julia 0.5_dev.

### ISSUE THREAD

**Issue by goedman** [brian-j-smith/Mamba.jl#81]
Hi Brian,

I know it is still very early, but just wanted to report this. Julia's package listing site show Mamba-0.8.1 passes on 0.5-dev, but Pkg.test("Mamba"), version 0.8.2, certainly fails with below error on 0.5-dev.

Regards,
Rob

---

...
Chain 3:  70% [0:00:00 of 0:00:01 remaining]
Chain 3:  80% [0:00:00 of 0:00:01 remaining]
Chain 3:  90% [0:00:00 of 0:00:01 remaining]
Chain 3: 100% [0:00:00 of 0:00:01 remaining]

WARNING: Method definition f(Any) in module Mamba at /Users/rob/.julia/v0.5/Mamba/src/output/modelchains.jl:64 overwritten at /Users/rob/.julia/v0.5/Mamba/src/output/modelchains.jl:64.
Iterations = 252:10000
Thinning interval = 2
Chains = 1,2,3
Samples per chain = 4875

Gelman, Rubin, and Brooks Diagnostic:
ERROR: LoadError: LoadError: BoundsError: attempt to access (4,1,false)
  at index [4]
 in plain_precision_heuristic at /Users/rob/.julia/v0.5/Showoff/src/Showoff.jl:97
 in showoff at /Users/rob/.julia/v0.5/Showoff/src/Showoff.jl:130
 in showoff at /Users/rob/.julia/v0.5/Showoff/src/Showoff.jl:112
 in mapslices at ./abstractarray.jl:1213
 in show at /Users/rob/.julia/v0.5/Mamba/src/output/chainsummary.jl:57
 in showall at /Users/rob/.julia/v0.5/Mamba/src/output/chainsummary.jl:44
 in showall at ./show.jl:1419
 in |> at ./operators.jl:204
 in include at ./boot.jl:262
 in include_from_node1 at ./loading.jl:417
 [inlined code] from /Users/rob/.julia/v0.5/Mamba/test/utils.jl:5
 in anonymous at ./no file:4294967295
 in include at ./boot.jl:262
 in include_from_node1 at ./loading.jl:417
 in process_options at ./client.jl:245
 in _start at ./client.jl:301
while loading /Users/rob/.julia/v0.5/Mamba/test/../doc/tutorial/line.jl, in expression starting on line 104
while loading /Users/rob/.julia/v0.5/Mamba/test/runtests.jl, in expression starting on line 32
====================================================[ ERROR: Mamba ]=====================================================

failed process: Process(`/Users/rob/Projects/Julia/julia/usr/bin/julia --check-bounds=yes --code-coverage=none --color=yes /Users/rob/.julia/v0.5/Mamba/test/runtests.jl`, ProcessExited(1)) [1]
# 

ERROR: Base.Pkg.PkgError("Mamba had test errors")
 in test at ./pkg/entry.jl:671
 in anonymous at ./pkg/dir.jl:31
 in cd at ./file.jl:47
 in cd at ./pkg/dir.jl:31
 in test at ./pkg.jl:228
 in eval at ./boot.jl:265

**Comment by brian-j-smith** [comment]
Hi Rob, good to hear from you.  I wonder if the error is coming from the Showoff package?   I haven't done any testing or development in julia 0.5-dev yet, but do plan on having Mamba be compatible with the next julia release as it gets closer.  So, the notice is appreciated.  It's also reassuring to see that 0.8.1 was passing testing on 0.5-dev.  Since none of the Mamba files mentioned in the error trace above changed in 0.8.2, the error might be due to a dev change - those can be somewhat of a moving target early in their cycles.

**Comment by goedman** [comment]
Hi Brian,

Yes, Showoff is indeed the culprit, the basic example in Showoff's README shows the problem.

Hopefully late this year I'll be done with the finite element project I took on and will have time to continue the MCMC explorations! But at least for Stan.jl I track the improvements you and Benjamin make to Mamba.jl!

Regards,
Rob
