### ISSUE TITLE
Question about storing warmup samples in Mamba chain objects.

### ISSUE THREAD

**Issue by goedman** [brian-j-smith/Mamba.jl#83]
Hi Brian,

Recently a question came up about storing the warmup samples in Stan. I erroneously assumed I could do that in Mamba chains and was kind of fooled by size(mambachain), size(mambachain.value) shows the real length. It is not hard to work around this by returning another mambachain (or array) with just the warmup samples in Stan.jl.

My question: Is storing warmup samples never a requirement for Mamba, e.g. for the NUTS sampler?

**Comment by brian-j-smith** [comment]
Right.  Storing warmup samples from NUTS is not required.  Internally, only sampled (and tuning parameter) values for the current iteration are needed to generate the next iteration.  Right now, Mamba does not return warmup/burnin iterations with the rationale being they may not constitute a Markov chain due to processing applied during that phase.

**Comment by goedman** [comment]
Thanks Brian, I'm guessing that the request came from models where tuning, and subsequent sampling, takes a very long time. Recently I saw some messages on the Stan mailing list about hours and even days. For now I will just return a Mamba chain with only warmup samples. Thanks for your help!

**Comment by bdeonovic** [comment]
Remember they can always set burnin to 0 and then determine post-hoc what fraction to cutoff.

**Comment by goedman** [comment]
Aah, thanks Benjamin, I think that might have been another possibility with CmdStan.

**Comment by brian-j-smith** [comment]
One thing to keep in mind is that the NUTS step size (epsilon) parameter is adaptively tuned during the warmup/burnin phase.  If burnin is set to 0, epsilon will not be tuned, and sampling may be pretty inefficient.
