### ISSUE TITLE
Error after updating RMath, PDMat, Distributions, etc.

### ISSUE THREAD

**Issue by goedman** [brian-j-smith/Mamba.jl#98]
Hi Brian,

Noticed below error after a recent update.

Regards,
Rob

julia> Pkg.installed("PDMats")
v"0.4.2"

julia> Pkg.installed("Distributions")
v"0.10.0"

julia> Pkg.installed("RMath")
v"0.1.2"

julia> Pkg.installed("DataFrames")
v"0.7.6"

julia> versioninfo()
Julia Version 0.4.6
Commit 2e358ce (2016-06-19 17:16 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> Pkg.installed("Mamba")
v"0.9.1"

julia> Pkg.test("Mamba")
INFO: Testing Mamba
Running tests:

>>> Testing ../doc/tutorial/line.jl

ERROR: LoadError: LoadError: LoadError: LoadError: TypeError: MvNormal: in T, expected T<:Real, got Type{Mamba.PDMats2.PBDiagMat}
 in include at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
 in require at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
 [inlined code] from /Users/rob/.julia/v0.4/Mamba/test/utils.jl:5
 in anonymous at no file:0
 in include at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
 in process_options at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/rob/.julia/v0.4/Mamba/src/distributions/extensions.jl, in expression starting on line 18
while loading /Users/rob/.julia/v0.4/Mamba/src/Mamba.jl, in expression starting on line 191
while loading /Users/rob/.julia/v0.4/Mamba/test/../doc/tutorial/line.jl, in expression starting on line 1
while loading /Users/rob/.julia/v0.4/Mamba/test/runtests.jl, in expression starting on line 32
====================================================[ ERROR: Mamba ]====================================================

failed process: Process(`/Applications/Julia-0.4.6.app/Contents/Resources/julia/bin/julia --check-bounds=yes --code-coverage=none --color=yes /Users/rob/.julia/v0.4/Mamba/test/runtests.jl`, ProcessExited(1)) [1]

========================================================================================================================
ERROR: Mamba had test errors
 in error at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
 in test at pkg/entry.jl:803
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71

julia>

**Comment by bdeonovic** [comment]
Might be related to: https://github.com/JuliaStats/Distributions.jl/issues/513 try upgrading to StatsFuns 0.2.2

**Comment by brian-j-smith** [comment]
Looks like it is the Distributions 0.10.0 update.  I just opened a pull request at https://github.com/JuliaLang/METADATA.jl/pull/5655 for an update to Mamba that fixes the issue.

**Comment by goedman** [comment]
Fixed! Thanks Brian.
