### ISSUE TITLE
Syntax for autoregressive (AR) models?

### ISSUE THREAD

**Issue by jae0** [brian-j-smith/Mamba.jl#99]
I am learning how to use Mamba and excited about the possibilities! So please bear with me. 

I would like to implement an AR model. For example, something like: 

  X[t] = f ( X[t-1] ) + error ; for some function f

In Bugs/Jags, this can be done as:

X[1] ~ dnorm ( 1, tau ) 
for (i in 2:N) {
  X[i] ~ dnorm(  X[i-1]*b , tau ) ;
}

In Mamba, is there a compact way of expressing this for a single stochastic vector X, or do I need to create X1, X2, ...XN separate scalar stochastic nodes? 

Thanks!

**Comment by bdeonovic** [comment]
You can do something similar in Mamba in the Model statement:

```julia

model = Model(
X = Stochastic(1,
    (tau, b) ->
      UnivariateDistribution[
        begin
          if i == 1
            Normal(1, 1 / tau)
          else
            Normal(X[i - 1] * b, 1 / tau)
          end
        end
        for i in 1:N
      ],
    false
  )
  ## other stochastic nodes...
)

**Comment by bdeonovic** [comment]
I'd highly recommend reading through the [examples](http://mambajl.readthedocs.io/en/latest/examples.html) to get a feel for the syntax

**Comment by jae0** [comment]
Yes, thanks. A stripped down test model based upon your suggestion (below) gives me an  error: "ERROR: UndefVarError: X not defined". Would you please tell me what I am doing incorrectly? 

```
data = Dict{Symbol, Any}(
  :N => 10,
  :Obs => rand(Normal(0.6, 0.1), 10) 
)

inits = [  Dict{Symbol, Any}(
  :alpha => 0.6,
  :beta => 0.5,
  :X => rand(Normal(0.5, 0.1), 10) 
) for i in 1:2 ]

model = Model(
  alpha = Stochastic( () -> Normal(0, 1)),
  beta = Stochastic( () -> Normal(0, 1)),
  X = Stochastic( 1, (beta, N) -> UnivariateDistribution[
    begin
      if i==1 
        Normal( 1, 1 ) 
      else 
        Normal( X[i-1] * beta , 1 ) 
      end
    end
    for i in 1:N ]
  ),
  Obs = Stochastic( 1, (X, alpha) -> Normal( X + alpha, 1) )  
)

sim = mcmc(model, data, inits, 1000, burnin=100, thin=1, chains=2)
 

```

**Comment by bdeonovic** [comment]
Try this

```julia
data = Dict{Symbol, Any}(
  :N => 10,
  :Obs => rand(Normal(0.6, 0.1), 10)
)

inits = [  Dict{Symbol, Any}(
  :alpha => 0.6,
  :beta => 0.5,
  :X => rand(Normal(0.5, 0.1), 10)
) for i in 1:2 ]

data[:Xcopy] = inits[1][:X]
model = Model(
  alpha = Stochastic( () -> Normal(0, 1)),
  beta = Stochastic( () -> Normal(0, 1)),
  X = Stochastic( 1, (beta, N, Xcopy) -> UnivariateDistribution[
    begin
      if i==1
        Normal( 1, 1 )
      else
        Normal( Xcopy[i-1] * beta , 1 )
      end
    end
    for i in 1:N ]
  )
)

setsamplers!(model, [Slice([:alpha, :beta], [1.0,1.0])])

sim = mcmc(model, data, inits, 1000, burnin=100, thin=1, chains=2)
```

**Comment by bdeonovic** [comment]
I'm not quite sure what is `obs` and do you mean for `X` to be different between chains? 

In regards to the error, the stochastic node should actually be something like:

```julia
  X = Stochastic( 1, (beta, N, X) -> 
    ... 
  ) 
```
However, you can't have loops (including self-loops) in the parameter network. To get around this you can have a copy of `X` in your data, however at this point I am confused since your `X` is different at each chain, so I am not quite sure of your model.

**Comment by jae0** [comment]
Right, I guess I should have explained more clearly. The problem of interest is to implement a model such as the one described here: https://www.stat.auckland.ac.nz/~millar/Bayesian/Surtuna.bugs .. a brief description of it can be found at the bottom of this message.

Yes, I think I understand. Each object in Julia/Mamba is its own entity (X) and self reference to an element of it would be considered a loop which is not permitted. The bugs syntax is finer grained and can treat each element of an object as a node. I was hoping I was wrong. I think the work-around is to create N stochastic nodes. Too bad. 

But thanks for the help.

---
WRT the model that I was trying to implement: it is essentially, it is an auto-regressive state space model (X, called "P" in the code linked above) with an additional observation model (Obs, called "I" in the linked code). 

X is an unobserved state that has some dynamical formulation ("_process_model_") that depends on its previous state(s) and some additional parameters, beta:

X[t] ~ Normal( _process_model_ (X[t-1], beta), tau )

And an observation model that is a function "_obs_model_" of the current unobserved system state and some set of parameters alpha:

Obs[t] ~ Normal ( _obs_model_( X[t], alpha), eta )

**Comment by brian-j-smith** [comment]
Individual nodes can also be generated with loops and macros, such as

```julia
N = 10
Nodes = Dict{Symbol,Any}()
Nodes[:X1] = Stochastic(() -> Normal(1, 1))
for i in 2:N
  global Xcur = symbol(string("X", i)),
         Xpre = symbol(string("X", i-1))
  @eval begin
    Nodes[:($Xcur)] = Stochastic(
      ($Xpre, beta) -> Normal($Xpre * beta, 1)
    )
  end
end

## Model specification (note the semicolon, ellipses, and commas)
model = Model(;
  Nodes...,
  beta = Stochastic(() -> Normal(0, 1))
)

draw(model)
```

**Comment by jae0** [comment]
Yes! That would work. Thank you!

Any way to permit self loops of this kind? Anyways, thanks again for an excellent tool. Looking foward to see where you take this!

Best wishes,
Jae

**Comment by bdeonovic** [comment]
As long as the node is a terminal node, without missing values you can do self loops to itself in the way Brian and I describe above. Otherwise you cannot do models with loops in the dependence graph.

**Comment by jae0** [comment]
Understood. Thanks again!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Benjamin DeonovicSent: Friday, July 22, 2016 6:48 PMTo: brian-j-smith/Mamba.jlReply To: brian-j-smith/Mamba.jlCc: Jae S. Choi; State changeSubject: Re: [brian-j-smith/Mamba.jl] Syntax for autoregressive (AR) models? (#99)As long as the node is a terminal node, without missing values you can do self loops to itself in the way Brian and I describe above. Otherwise you cannot do models with loops in the dependence graph. 

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
